# Site settings
author: Joey Adam Cho
title: Unique & creative traveler
header-img: img/home-bg.png
email: cjy12182000@naver.com
copyright_name: Joey Adam Cho
description: > # this means to ignore newlines until "baseurl:"
  Interest in : Web development | Machine Learning | Computer Vision
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Joeycho

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
