# Site settings
title: 
header-img: img/home-bg.png
email: cjy12182000@naver.com
copyright_name: Joeycho
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Joeycho
learn_profile: Joeycho
email_username: cjy12182000@naver.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
